
import { Courier_Prime } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "voidler",
  description: "Generated by create next app",
};

const courier = Courier_Prime({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  variable: "--font-courier",
});

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <body className={`${courier.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
